export const leaderboardData = {
    week: [
      { player: "Pierwsza", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "870" },
      { player: "Richard Gran", score: "800" },
      { player: "John Michael", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "870" },
      { player: "Richard Gran", score: "800" },
      { player: "John Michael", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "1" },
      { player: "Richard Gran", score: "1" },
      { player: "John Michael", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "870" },
      { player: "Richard Gran", score: "800" },
      { player: "John Michael", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "870" },
      { player: "Richard Gran", score: "800" },
      { player: "John Michael", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "1" },
      { player: "Richard Gran", score: "1" },
      { player: "John Michael", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "870" },
      { player: "Richard Gran", score: "800" },
      { player: "John Michael", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "870" },
      { player: "Richard Gran", score: "800" },
      { player: "John Michael", score: "1200" },
      { player: "Alexa Liras", score: "1100" },
      { player: "Laurent Perrier", score: "950" },
      { player: "Michael Levi", score: "1" },
      { player: "Richard Gran", score: "1" },
    ],
    month: [
      { player: "Pierwsza 2", score: "1500" },
      { player: "John Michael", score: "1400" },
      { player: "Laurent Perrier", score: "1300" },
      { player: "Michael Levi", score: "1200" },
      { player: "Richard Gran", score: "1100" },
    ],
    "all-time": [
      { player: "Pierwsza3", score: "2000" },
      { player: "Alexa Liras", score: "1900" },
      { player: "John Michael", score: "1800" },
      { player: "Michael Levi", score: "1700" },
      { player: "Richard Gran", score: "1600" },
    ],
  };
  